import PALLETTE from '../../helpers/pallette';
import AccentText from '../common/AccentText/AccentText';
import MainText from '../common/MainText/MainText';
import * as S from './About.styled';

import aboutApe from '../../assets/images/aboutApe.png';

function About() {
  return (
    <S.Section className="container" id="about">
      <S.Container>
        <S.TextBox>
          <S.Title el="p" fs="40px">
            A story that started with{' '}
            <AccentText el="span" fs="40px" color={PALLETTE.accent}>
              one simple{' '}
            </AccentText>
            <AccentText
              el="span"
              fs="40px"
              color={PALLETTE.accent}
              display="block"
            >
              ape
            </AccentText>
          </S.Title>

          <S.Description talign="right" mt="16px" lh="1.19" mb="36px">
            <MainText el="span" talign="right" display="block">
              Who got{' '}
            </MainText>{' '}
            fed up with boring and hypocritic commonplace this is how the idea
            of escaping and dynamic journey on the
            <span> yacht</span>
          </S.Description>
        </S.TextBox>

        <S.Div>
          <S.IconCross fill={PALLETTE.textLightMain} width={24} height={24} />

          <MainText fs="12px" lh="1.16" talign="center" mt="16px" mb="40px">
            Each artwork in the collection tells a story of one journey. arts
            are randomly generated by users
          </MainText>
        </S.Div>

        <S.AboutImage
          src={aboutApe}
          alt="A cool ape with glasses and a cap"
          width="216px"
          height="292px"
        />
      </S.Container>
    </S.Section>
  );
}

export default About;
